#!/bin/bash

docker-compose -H ssh://pi -f ~/Docker-Compose-Containers/simulator/docker-compose.yml up --build -d && \\
docker-compose -H ssh://pi -f ~/Docker-Compose-Containers/thermocouples/docker-compose.yml up --build -d
