#!/bin/bash

docker-compose -f ~/Docker-Compose-Containers/kafka/docker-compose.yml up --build -d && docker-compose -f ~/Docker-Compose-Containers/timescaledb/docker-compose.yml up --build -d && docker-compose -f ~/Docker-Compose-Containers/grafana/docker-compose.yml up --build -d && docker-compose -f ~/Docker-Compose-Containers/consumer/docker-compose.yml up --build -d

