#!/bin/bash

docker-compose -H ssh://pi@191.30.80.100 -f ~/Docker-Compose-Containers/simulator/docker-compose.yml down && docker-compose -H ssh://pi@191.30.80.100 -f ~/Docker-Compose-Containers/thermocouples/docker-compose.yml down
