version: '3'
services:
  consumer:
    container_name: consumer
    build:
      context: ./consumer
    stdin_open: true
    tty: true

  producer:
    container_name: producer
    build:
      context: ./producer
    stdin_open: true
    tty: true
    depends_on:
      - consumer

