  grafana:
    image: grafana/grafana:8.1.2
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./defaults.ini:/usr/share/grafana/conf/defaults.ini
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources/
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards/
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - 3000:3000
