{
 "title": "Capstone Expo",
 "time": { "from": "now-1s", "to": "now" },
 "refresh": "50ms",
 "panels": [
  { "title": "Main Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Thermocouple channels",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  thermocouple_temperature\nFROM maxchipdata\nWHERE\n  $__timeFilter(\"time\") AND\n  data_pin = 23 AND\n  reference_juntion_temperature != 0 AND\n  thermocouple_temperature != 0\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  thermocouple_temperature\nFROM maxchipdata\nWHERE\n  $__timeFilter(\"time\") AND\n  data_pin = 26 AND\n  reference_juntion_temperature != 0 AND\n  thermocouple_temperature != 0\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  thermocouple_temperature\nFROM maxchipdata\nWHERE\n  $__timeFilter(\"time\") AND\n  data_pin = 5 AND\n  reference_juntion_temperature != 0 AND\n  thermocouple_temperature != 0\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  thermocouple_temperature\nFROM maxchipdata\nWHERE\n  $__timeFilter(\"time\") AND\n  data_pin = 22 AND\n  reference_juntion_temperature != 0 AND\n  thermocouple_temperature != 0\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  thermocouple_temperature\nFROM maxchipdata\nWHERE\n  $__timeFilter(\"time\") AND\n  data_pin = 17 AND\n  reference_juntion_temperature != 0 AND\n  thermocouple_temperature != 0\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  thermocouple_temperature\nFROM maxchipdata\nWHERE\n  $__timeFilter(\"time\") AND\n  data_pin = 13 AND\n  reference_juntion_temperature != 0 AND\n  thermocouple_temperature != 0\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  thermocouple_temperature\nFROM maxchipdata\nWHERE\n  $__timeFilter(\"time\") AND\n  data_pin = 4 AND\n  reference_juntion_temperature != 0 AND\n  thermocouple_temperature != 0\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Simulated Data (0-10, 4-20)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  data_value\nFROM sensordata\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Thermocouple 4",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(thermocouple_temperature) AS \"thermocouple_temperature\"\nFROM maxchipdata\nWHERE\n  $__timeFilter(\"time\") AND\n  data_pin = 4 AND\n  reference_juntion_temperature != 0 AND\n  thermocouple_temperature != 0\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Thermocouple 5",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(thermocouple_temperature) AS \"thermocouple_temperature\"\nFROM maxchipdata\nWHERE\n  $__timeFilter(\"time\") AND\n  data_pin = 5 AND\n  reference_juntion_temperature != 0 AND\n  thermocouple_temperature != 0\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Thermocouple 13",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(thermocouple_temperature) AS \"thermocouple_temperature\"\nFROM maxchipdata\nWHERE\n  $__timeFilter(\"time\") AND\n  data_pin = 13 AND\n  reference_juntion_temperature != 0 AND\n  thermocouple_temperature != 0\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Thermocouple 17",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(thermocouple_temperature) AS \"thermocouple_temperature\"\nFROM maxchipdata\nWHERE\n  $__timeFilter(\"time\") AND\n  data_pin = 17 AND\n  reference_juntion_temperature != 0 AND\n  thermocouple_temperature != 0\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Thermocouple 23",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(thermocouple_temperature) AS \"thermocouple_temperature\"\nFROM maxchipdata\nWHERE\n  $__timeFilter(\"time\") AND\n  data_pin = 23 AND\n  reference_juntion_temperature != 0 AND\n  thermocouple_temperature != 0\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Thermocouple 26",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(thermocouple_temperature) AS \"thermocouple_temperature\"\nFROM maxchipdata\nWHERE\n  $__timeFilter(\"time\") AND\n  data_pin = 26 AND\n  reference_juntion_temperature != 0 AND\n  thermocouple_temperature != 0\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  { "title": "Individual Thermocouples", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Thermocouple 4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  thermocouple_temperature\nFROM maxchipdata\nWHERE\n  $__timeFilter(\"time\") AND\n  reference_juntion_temperature != 0 AND\n  thermocouple_temperature != 0 AND\n  data_pin = 4\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Thermocouple 5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  thermocouple_temperature\nFROM maxchipdata\nWHERE\n  $__timeFilter(\"time\") AND\n  reference_juntion_temperature != 0 AND\n  thermocouple_temperature != 0 AND\n  data_pin = 5\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Thermocouple 13",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  thermocouple_temperature\nFROM maxchipdata\nWHERE\n  $__timeFilter(\"time\") AND\n  reference_juntion_temperature != 0 AND\n  thermocouple_temperature != 0 AND\n  data_pin = 13\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Thermocouple 17",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  thermocouple_temperature\nFROM maxchipdata\nWHERE\n  $__timeFilter(\"time\") AND\n  reference_juntion_temperature != 0 AND\n  thermocouple_temperature != 0 AND\n  data_pin = 17\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Thermocouple 23",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  thermocouple_temperature\nFROM maxchipdata\nWHERE\n  $__timeFilter(\"time\") AND\n  reference_juntion_temperature != 0 AND\n  thermocouple_temperature != 0 AND\n  data_pin = 23\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Thermocouple 23",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  thermocouple_temperature\nFROM maxchipdata\nWHERE\n  $__timeFilter(\"time\") AND\n  reference_juntion_temperature != 0 AND\n  thermocouple_temperature != 0 AND\n  data_pin = 23\nORDER BY 1"
    }
   ]
  }
 ]
}